export const metadata = {
  title: "Analytics Page",
  description: "Generated by create next app",
};

const AnalyticsPage = () => {

  return (
    <div className=' p-4 '> 

    <h1 className='text-4xl '>🪕 AnalyticsPage page </h1>
    <a className='text-blue-300 ' href='http://localhost:3000/'>Home Page</a>
    <p className="mt-10 ">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tempora dicta nostrum accusantium voluptates ullam magni voluptatem, vel atque. Maxime totam cum, recusandae reprehenderit 
    </p>
    </div>
  )
}

export default AnalyticsPage