## First run the server: `npm run dev`


### Get profile header test api
GET  http://localhost:3000/api/profile
Content-Type: application/json
Authorization: Bearer123456


### Get all comments
GET  http://localhost:3000/api/comments
Content-Type: application/json

### Filtered  comments
GET  http://localhost:3000/api/comments?query=2
Content-Type: application/json

### Create comments
POST http://localhost:3000/api/comments
Content-Type: application/json

{
    "text":"Comment - 12"
}

### Get single comment by id
GET  http://localhost:3000/api/comments/30
Content-Type: application/json

### Update comment
PATCH   http://localhost:3000/api/comments/3
Content-Type: application/json

{
    "text":"updated comment four"
}

### Delete semester
DELETE  http://localhost:3000/api/comments/3
Content-Type: application/json


