
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import Link from 'next/link'
import CustomLink from "./components/CustomLink";

// export const metadata = {
//   title: "Basic-Routing",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="p-4 border-b border-blue-400  font-semibold cursor-pointer  ">
        <ul className=" flex gap-5 ">
          {/* <li>
            <Link href="/">Home</Link>
          </li> */}
          <li>
            <CustomLink path="/">Home</CustomLink>
          </li>
          <li>
            <CustomLink path="/dashboard">Dashboard</CustomLink>
            {/* <Link href="/dashboard">Dashboard</Link> */}
          </li>
          <li>
            <CustomLink path="/dashboard/analytics">Analytics</CustomLink>
            {/* <Link href="/dashboard/analytics">Analytics</Link> */}
          </li>
          <li>
            <CustomLink path="/dashboard/settings">Settings</CustomLink>
          </li>
          <li>
            <CustomLink path="/dashboard/profileA">Profile-A</CustomLink>
          </li>
          <li>
            <CustomLink path="/heavy">Heavy</CustomLink>
          </li>
          <li>
            <CustomLink path="/blogs">BlogList</CustomLink>
          </li>
          <li>
            <CustomLink path="/games">GameList</CustomLink>
          </li>
  
        </ul>
      </nav>
      {children}
      <hr />
      <footer className=" text-center font-semibold mt-96 ">Basic routing 2024 Next js 14 </footer>
      </body>
    </html>
  );
}
