import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Basic-Routing",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="p-4 border-b border-blue-400  font-semibold cursor-pointer  ">
        <ul className=" flex gap-5 ">
          <li>Home</li>
          <li>About</li>
          <li> <a className=" bg-indigo-300   " href="http://localhost:3000/dashboard/analytics">Dashboard</a> </li>
        </ul>
      </nav>
      {children}
      <hr />
      <footer className=" text-center font-semibold">basic routing 2024 Next js 14 </footer>
      </body>
    </html>
  );
}
