import Image from "next/image";


export const metadata = {
  title: "HomePage",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="homeDiv">
      <h1 className=" text-2xl text-center mt-5 font-bold">Home Page of RootLayout</h1>
      <div className="mt-10">
        This is the home page content of app directory
      </div>
    </div>
  );
}
