## First run the server: `npm run dev`


### Get all photos
GET  http://localhost:3000/api/photos
Content-Type: application/json



### Get single photo by id
GET  http://localhost:3000/api/photos/94a7e01b-8576-4d18-8b84-6ae588db02d9
Content-Type: application/json

### Filtered  comments
GET  http://localhost:3000/api/comments?query=2
Content-Type: application/json

### Create comments
POST http://localhost:3000/api/comments
Content-Type: application/json

{
    "text":"Comment - 12"
}

### Get single comment by id
GET  http://localhost:3000/api/comments/30
Content-Type: application/json

### Update comment
PATCH   http://localhost:3000/api/comments/3
Content-Type: application/json

{
    "text":"updated comment four"
}

### Delete semester
DELETE  http://localhost:3000/api/comments/3
Content-Type: application/json

